### ISSUE TITLE
Unable to connect: Failed to read thrift: ...

### ISSUE THREAD

**Issue by Deaddy** [bitlbee/bitlbee-facebook#197]
This happens to me since yesterday evening, when trying to connect to facebook.

` facebook - Error: Failed to read thrift: facebook-api.c:1929 fb_api_cb_publish_pt: 
              assertion 'fb_thrift_read_stop(thft)' failed`

The libpurple-facebook plugin seems to have the same problem now:
https://github.com/dequis/purple-facebook/issues/494

This does not seem to be a dupe of https://github.com/bitlbee/bitlbee-facebook/issues/151

I tried current git checkout (-9999 version in funtoo), 1.1.2 and 1.2.0.

**Comment by scorpion7-7** [comment]
Not sure where the issue that I opened went, but yes - same issue.  Seemed to be "out of the blue" that this started happening.  Its results in a constant "modify account/reconnect" state, no entries in the buddy list, but I'm still receiving 'some' random messages.  Which is odd.  It must be connecting "long enough" to get a message, but then disconnects before it can obtain anything else. (not sure if that detail is helpful).

**Comment by Ryan659** [comment]
Looks like it was fixed in the libpurple side here: https://github.com/dequis/purple-facebook/pull/480 (though not released yet officially it seems)

I applied the same change on this repo and it doesn't seem to have any issues

**Comment by Deaddy** [comment]
Cool, thanks for the work. Weirdly enough though, it does not seeem to fix the issue for me, even after additionally changing the version to make really sure bitlbee has the updated plugin after restarting the bitlbee service. I think I'll give it another try this weekend, maybe I was just being stoopid somewhere.

**Comment by oliverralbertini** [comment]
@Deaddy https://github.com/dequis/purple-facebook/pull/480 didn't fix it for me either, but could you try https://github.com/bitlbee/bitlbee-facebook/pull/199? I'm not sure what has changed, but seems like wrapping the final `fb_read_thrift_stop()` with a check (`fb_read_thrift_isstop()`) prevents the error.

@dequis can probably see if this approach makes sense.

**Comment by dequis** [comment]
Fix looks good, thanks.

Buuuut travis is broken, and that's required for the release process. Anyone want to fix it? Probably involves changing distro version to 16.04 or 18.04 and fixing up installs. I gave it a shot yesterday but decided it's not a very good use of the little motivation I have to work on this.

**Comment by Deaddy** [comment]
Sorry for the long non-response, but I wanted to say thanks, @oliverralbertini 's PR works for me.

For me this issue could be closed, I install from git anyway, but maybe you want to keep it open until you have made a release.

**Comment by Pfelelep** [comment]
Greetings, could someone help me to fix the plugin problem myself? I am afraid I have no idea how to even start. :/

**Comment by nuxi** [comment]
@dequis I fixed the CI https://github.com/bitlbee/bitlbee-facebook/pull/201

**Comment by dequis** [comment]
Thank you! Merged that and #199

**Comment by dequis** [comment]
I'll make a release after #200 has a fix

**Comment by dequis** [comment]
https://github.com/bitlbee/bitlbee-facebook/releases/tag/v1.2.1
